### ISSUE TITLE
error on heroku

### ISSUE THREAD

**Issue by gVallverdu** [ArnaudMarcel/Covid_Analysis#2]
Bonjour, 
Il est possible que l'erreur sur heroku vienne du Procfile.

Dans votre `Procfile` vous avez:
```
web: gunicorn app:server
```

Ce qui veut dire que `gunicorn` ira chercher la variable `server` dans le fichier `app.py`. Du coup, moi dans mon fichier NBA j'ai ça:

```py
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
server = app.server
```

Dans votre fichier `app.py` vous avez créé une nouvelle classe, `CustomDash` qui hérite de la classe `Dash`: 

```py
class CustomDash(dash.Dash):
    
    def setLayout(self, options):
        self.layout = html.Div([
```

Et un peu plus loin vous avez:
```py
app = CustomDash(title='Analysis', external_scripts=external_scripts)
app.setLayout(options)
```

Vous n'avez jamais initialisé la variable `server` il faudrait rajouter cette ligne dans votre fichier `app.py` pour que ça marche sur heroku:
```py
server = app.server
```

En parallèle, il y a des petits soucis de CSS. Si on élargit trop la page, les dropdowns bougent et disparaissent.

De même le graphique est assez peu lisible.

Dernière chose, si je pinaille un peu, c'est dommage que le dropdown sur le département dépendent du dropdown sur la quantité que l'on veut afficher. Par exemple, si je veux afficher les infos sur le 66, chaque fois que je change de données je dois rechercher le département. 

Vous pouvez répondre ici si vous avez d'autres erreurs de déploiement. Pensez éventuellement à mettre une copie de la sortie pour voir l'erreur.
Bon courage

**Comment by ArnaudMarcel** [comment]
Bonsoir,

Merci pour votre aide, on a suivi vos instructions mais il y'a toujours une erreur sur heroku :

**Comment by ArnaudMarcel** [comment]
Problème résolu :

```Python
app = CustomDash(title = 'Corodata', external_scripts = external_scripts)
--> app = CustomDash(__name__, title = 'Corodata', external_scripts = external_scripts)
```
```Python
app.run_server(debug = False) 
--> if __name__ == '__main__':
    app.run_server(debug = True)
```

**Comment by gVallverdu** [comment]
Bonjour
L'erreur venait d'où finalement ?
C'est sur l'exécution à la fin du `app.run_server` ?

**Comment by ArnaudMarcel** [comment]
L'erreur venait de l'instanciation de l'objet Dash : j'avais oublié de passer en paramètre la variable système __name__.
```python
app = CustomDash(__name__, title = 'Corodata', external_scripts = external_scripts)
```
Donc l'application Dash ne pouvait pas se greffer sur l'application Flask.
